#!/usr/bin/env node

const config = require('../config');
const prettier = require('prettier');
const fs = require('fs');
const expand = require('glob-expand');
const colors = require('colors');

const beautify = file => {
  fs.readFile(file, 'utf8', (err, content) => {
    if (err) {
      console.error(err);
      process.exit(1);
    }

    let data = prettier.format(content.toString(), {
      tabWidth: 2,
      useTabs: false,
      semi: true,
      singleQuote: true,
      bracketSpacing: true,
      parser: 'babylon'
    });

    if (data) {
      fs.writeFile(file, data, err => {
        if (err) {
          console.error(err);
          process.exit(1);
        }
        console.log(colors.green(`${file} beautified.`));
      });
    }
  });
};

const files = expand(
  {
    cwd: process.cwd()
  },
  config.scripts.source
);

files.forEach(file => {
  beautify(file);
});
