#!/usr/bin/env node

const config = require('../config');
const del = require('del');
const colors = require('colors');

del([config.svgs.build]).then(paths => {
  console.log(colors.green('Svg dist files cleaned.'));
});
