#!/usr/bin/env node

const config = require('../config');
const del = require('del');
const colors = require('colors');

del([config.images.build]).then(paths => {
  console.log(colors.green('Images dist files cleaned.'));
});
