#!/usr/bin/env node

const config = require('../config');
const del = require('del');
const colors = require('colors');

del([config.favicon.build]).then(paths => {
  console.log(colors.green('Favicon files cleaned.'));
});
