#!/usr/bin/env node

const browser = require("./browser");;
const config = require('../config');
const colors = require('colors');

browser.init({
  server: {
    baseDir: config.html.build,
  },
  port: 4000,
  notify: true,
  open: true,
  //watch: true
}, () => {
  console.log(colors.green('Browser starting'));
});
