#!/usr/bin/env node

const config = require('../config');
const fs = require('fs');
const colors = require('colors');
const AssetsManager = require('assets-manager');

const manager = new AssetsManager(config.vendor.manifest, config.vendor);

manager.copyPackages().then(()=>{
  console.log(colors.green('Vendor copied.'));
});